In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.shape

(10000, 14)

In [5]:
df = df.drop(columns = ['RowNumber', 'CustomerId', 'Surname'])

In [6]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [8]:
df.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [9]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [10]:
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.impute import SimpleImputer
# from sklearn.compose import make_column_transformer

# transformer = make_column_transformer(
#     (OneHotEncoder(drop='first'), ['Geography', 'Gender']),
#     (SimpleImputer(strategy='median'), ['Age']),
#     remainder='passthrough'
# )

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [14]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True, dtype=int)

In [15]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0

In [16]:
X = df.drop(columns = ['Exited'])
y = df['Exited']

In [17]:
print(X.shape, y.shape)

(10000, 11) (10000,)

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [19]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(8000, 11) (8000,)
(2000, 11) (2000,)

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input

In [29]:
model = Sequential()

model.add(Input(shape=(11, ))) # Input layer
model.add(Dense(6, activation='sigmoid')) # Hidden Layer
model.add(Dense(3, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid')) # Output Layer
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [30]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 6)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 3)              │            21 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.fit(X_train_scaled, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
 62/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1831 - loss: 1.0581

I0000 00:00:1792755952.715843    4143 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.2281 - loss: 0.8570 - val_accuracy: 0.6206 - val_loss: 0.6844
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7886 - loss: 0.6013 - val_accuracy: 0.7975 - val_loss: 0.5441
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7972 - loss: 0.5174 - val_accuracy: 0.7975 - val_loss: 0.4994
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7972 - loss: 0.4889 - val_accuracy: 0.7975 - val_loss: 0.4827
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7972 - loss: 0.4764 - val_accuracy: 0.7975 - val_loss: 0.4739
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7972 - loss: 0.4685 - val_accuracy: 0.7975 - val_loss: 0.4676
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7972 - loss: 0.4618 - val_accuracy: 0.7975 - val_loss: 0.4620
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7972 - loss: 0.4555 - val_accuracy: 0.7975 - val_loss: 0.4568
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7972 - loss: 0.4498 - val_accuracy: 0.7975 - val_loss: 0.4520
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7972 - loss: 0.4446 - val_accuracy: 0.7975 - val_loss: 0.4479
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7972 - loss: 0.4401 - val_accuracy: 0.7975 - val_loss: 0.4444
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7972 - loss: 0.4364 - val_accuracy: 0.7975 - val_loss: 0.4416
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8000 - loss: 0.4333 - val_accuracy: 0.8062 - val_loss: 0.4393
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8058 - loss: 0.4308 - val_accuracy: 0.8081 - val_loss: 0.4373
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8128 - loss: 0.4287 - val_accuracy: 0.8112 - val_loss: 0.4358
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8181 - loss: 0.4269 - val_accuracy: 0.8112 - val_loss: 0.4343
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8197 - loss: 0.4253 - val_accuracy: 0.8138 - val_loss: 0.4329
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8214 - loss: 0.4239 - val_accuracy: 0.8138 - val_loss: 0.4315
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8219 - loss: 0.4225 - val_accuracy: 0.8144 - val_loss: 0.4300
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8234 - loss: 0.4211 - val_accuracy: 0.8163 - val_loss: 0.4286
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8239 - loss: 0.4197 - val_accuracy: 0.8181 - val_loss: 0.4270
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8248 - loss: 0.4184 - val_accuracy: 0.8175 - val_loss: 0.4258
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8261 - loss: 0.4171 - val_accuracy: 0.8188 - val_loss: 0.4241
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8275 - loss: 0.4158 - val_accuracy: 0.8200 - val_loss: 0.4229
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8280 - loss: 0.4145 - val_accuracy: 0.8244 - val_loss: 0.4214
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8308 - loss: 0.4135 - val_accuracy: 0.8256 - val_loss: 0.4204
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8323 - loss: 0.4124 - val_accuracy: 0.8275 - val_loss: 0.4195
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8328 - loss: 0.4113 - val_accuracy: 0.8281 - val_loss: 0.4185
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8336 - loss: 0.4104 - val_accuracy: 0.8275 - val_loss: 0.4177
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8348 - loss: 0.4096 - val_accuracy: 0.8269 - val_loss: 0.4171
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8348 - loss: 0.4088 - val_accuracy: 0.8275 - val_loss: 0.4164
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8342 - loss: 0.4081 - val_accuracy: 0.8281 - val_loss: 0.4159
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8353 - loss: 0.4075 - val_accuracy: 0.8294 - val_loss: 0.4152
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8364 - loss: 0.4069 - val_accuracy: 0.8306 - val_loss: 0.4146
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8363 - loss: 0.4063 - val_accuracy: 0.8306 - val_loss: 0.4142
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8369 - loss: 0.4057 - val_accuracy: 0.8300 - val_loss: 0.4140
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8372 - loss: 0.4052 - val_accuracy: 0.8313 - val_loss: 0.4137
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8375 - loss: 0.4047 - val_accuracy: 0.8319 - val_loss: 0.4132
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8366 - loss: 0.4043 - val_accuracy: 0.8313 - val_loss: 0.4129
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8369 - loss: 0.4041 - val_accuracy: 0.8313 - val_loss: 0.4128
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8380 - loss: 0.4036 - val_accuracy: 0.8313 - val_loss: 0.4126
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8388 - loss: 0.4033 - val_accuracy: 0.8288 - val_loss: 0.4126
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8392 - loss: 0.4030 - val_accuracy: 0.8294 - val_loss: 0.4124
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8388 - loss: 0.4027 - val_accuracy: 0.8294 - val_loss: 0.4121
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8403 - loss: 0.4025 - val_accuracy: 0.8294 - val_loss: 0.4120
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8397 - loss: 0.4022 - val_accuracy: 0.8306 - val_loss: 0.4118
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8398 - loss: 0.4020 - val_accuracy: 0.8306 - val_loss: 0.4117
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8405 - loss: 0.4016 - val_accuracy: 0.8281 - val_loss: 0.4116
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8405 - loss: 0.4014 - val_accuracy: 0.8306 - val_loss: 0.4117
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8402 - loss: 0.4012 - val_accuracy: 0.8300 - val_loss: 0.4113
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8402 - loss: 0.4010 - val_accuracy: 0.8300 - val_loss: 0.4112
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8403 - loss: 0.4009 - val_accuracy: 0.8300 - val_loss: 0.4112
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8402 - loss: 0.4007 - val_accuracy: 0.8300 - val_loss: 0.4112
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8408 - loss: 0.4005 - val_accuracy: 0.8300 - val_loss: 0.4115
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8405 - loss: 0.4004 - val_accuracy: 0.8300 - val_loss: 0.4112
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8403 - loss: 0.4002 - val_accuracy: 0.8300 - val_loss: 0.4111
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8406 - loss: 0.4001 - val_accuracy: 0.8294 - val_loss: 0.4111
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8408 - loss: 0.3999 - val_accuracy: 0.8306 - val_loss: 0.4109
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8403 - loss: 0.3997 - val_accuracy: 0.8294 - val_loss: 0.4108
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8405 - loss: 0.3996 - val_accuracy: 0.8306 - val_loss: 0.4107
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8398 - loss: 0.3995 - val_accuracy: 0.8300 - val_loss: 0.4106
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8406 - loss: 0.3993 - val_accuracy: 0.8288 - val_loss: 0.4104
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8409 - loss: 0.3993 - val_accuracy: 0.8306 - val_loss: 0.4107
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8397 - loss: 0.3992 - val_accuracy: 0.8306 - val_loss: 0.4108
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8402 - loss: 0.3989 - val_accuracy: 0.8300 - val_loss: 0.4107
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8398 - loss: 0.3989 - val_accuracy: 0.8281 - val_loss: 0.4105
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8397 - loss: 0.3987 - val_accuracy: 0.8281 - val_loss: 0.4103
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8386 - loss: 0.3987 - val_accuracy: 0.8288 - val_loss: 0.4104
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8402 - loss: 0.3985 - val_accuracy: 0.8300 - val_loss: 0.4105
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8397 - loss: 0.3984 - val_accuracy: 0.8288 - val_loss: 0.4102
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8402 - loss: 0.3982 - val_accuracy: 0.8281 - val_loss: 0.4102
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8395 - loss: 0.3982 - val_accuracy: 0.8288 - val_loss: 0.4103
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8400 - loss: 0.3981 - val_accuracy: 0.8275 - val_loss: 0.4109
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8398 - loss: 0.3982 - val_accuracy: 0.8275 - val_loss: 0.4109
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8398 - loss: 0.3980 - val_accuracy: 0.8281 - val_loss: 0.4102
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8394 - loss: 0.3978 - val_accuracy: 0.8275 - val_loss: 0.4105
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8398 - loss: 0.3978 - val_accuracy: 0.8275 - val_loss: 0.4105
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8391 - loss: 0.3976 - val_accuracy: 0.8288 - val_loss: 0.4106
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8402 - loss: 0.3976 - val_accuracy: 0.8281 - val_loss: 0.4105
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8402 - loss: 0.3975 - val_accuracy: 0.8288 - val_loss: 0.4102
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8391 - loss: 0.3974 - val_accuracy: 0.8281 - val_loss: 0.4104
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8400 - loss: 0.3973 - val_accuracy: 0.8281 - val_loss: 0.4100
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8405 - loss: 0.3972 - val_accuracy: 0.8294 - val_loss: 0.4099
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8406 - loss: 0.3970 - val_accuracy: 0.8275 - val_loss: 0.4101
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8398 - loss: 0.3969 - val_accuracy: 0.8281 - val_loss: 0.4103
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8406 - loss: 0.3969 - val_accuracy: 0.8281 - val_loss: 0.4099
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8403 - loss: 0.3968 - val_accuracy: 0.8269 - val_loss: 0.4101
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8413 - loss: 0.3968 - val_accuracy: 0.8281 - val_loss: 0.4097
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8394 - loss: 0.3967 - val_accuracy: 0.8275 - val_loss: 0.4098
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8397 - loss: 0.3965 - val_accuracy: 0.8281 - val_loss: 0.4103
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8402 - loss: 0.3966 - val_accuracy: 0.8281 - val_loss: 0.4101
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8398 - loss: 0.3964 - val_accuracy: 0.8275 - val_loss: 0.4097
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8402 - loss: 0.3962 - val_accuracy: 0.8281 - val_loss: 0.4099
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8406 - loss: 0.3963 - val_accuracy: 0.8281 - val_loss: 0.4098
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8394 - loss: 0.3962 - val_accuracy: 0.8281 - val_loss: 0.4098
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8398 - loss: 0.3960 - val_accuracy: 0.8281 - val_loss: 0.4099
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8395 - loss: 0.3959 - val_accuracy: 0.8281 - val_loss: 0.4099
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8408 - loss: 0.3959 - val_accuracy: 0.8294 - val_loss: 0.4100
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8400 - loss: 0.3960 - val_accuracy: 0.8294 - val_loss: 0.4098
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8406 - loss: 0.3957 - val_accuracy: 0.8281 - val_loss: 0.4095

In [32]:
y_pred = model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

In [33]:
y_pred_formatted = np.where(y_pred > 0.5, 1, 0)

In [34]:
from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, y_pred_formatted))

Accuracy: 0.836